
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      #- uses: rokibhasansagar/actions_cleanup-ghactions@v1
      #- name: Install Expect
        #run: sudo apt-get install -qy expect
      - name: Keepalive
        run: |
          cat << EOK > /tmp/keepalive.sh
          #!/bin/bash
          # keep this so that it can be killed from other command
          echo \$$ > /tmp/keepalive.pid
          # keepalive loop
          while true; do
            printf " \n" && sleep 1200
          done
          EOK
          chmod a+x /tmp/keepalive.sh
      - name: Try Run loop
        run: |
          /tmp/keepalive.sh & printf " \n"
        #  expect -c "
        #  spawn git --help
        #  set timeout -1
        #  interact"
