
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: rokibhasansagar/actions_cleanup-ghactions@v1
      - name: Install Expect
        run: sudo apt-get install -qy expect
      - name: Keepalive
        timeout-minutes: 140
        run: |
          while true; do
            printf ".\n" && sleep 1200
          done
          git --version
      - name: Expect
        timeout-minutes: 340
        run: |
          expect -c "
          set timeout -1
          spawn git --help
          "
          git --version
        #  spawn git --help
        #  set timeout -1
        #  interact"
